package test3.db.entity;

import java.time.LocalDateTime;

public class Test3 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test3.id
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	protected Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test3.enum_test
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	protected Test3EntityEnum enumTest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test3.update_date
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	protected LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test3.id
	 * @return  the value of test3.id
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test3.id
	 * @param id  the value for test3.id
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test3.enum_test
	 * @return  the value of test3.enum_test
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public Test3EntityEnum getEnumTest() {
		return enumTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test3.enum_test
	 * @param enumTest  the value for test3.enum_test
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public void setEnumTest(Test3EntityEnum enumTest) {
		this.enumTest = enumTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test3.update_date
	 * @return  the value of test3.update_date
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test3.update_date
	 * @param updateDate  the value for test3.update_date
	 * @mbg.generated  Sat Jan 14 23:45:30 JST 2017
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public String toString() {
		return "Test3 [id=" + id + ", enumTest=" + enumTest + ", updateDate=" + updateDate + "]";
	}
}