package test3.db.mapper;

import test3.db.entity.Test3;

public interface Test3Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	int insert(Test3 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	int insertSelective(Test3 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	Test3 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Test3 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test3
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Test3 record);
}