package test3.db.mapper;

import test3.db.entity.Test2;

public interface Test2Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	int insert(Test2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	int insertSelective(Test2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	Test2 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	int updateByPrimaryKeySelective(Test2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test2
	 * @mbg.generated  Wed Dec 28 00:23:01 JST 2016
	 */
	int updateByPrimaryKey(Test2 record);
}