spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: user
    password: password
  h2:
    console:
      enabled: false

mybatis:
  type-handlers-package: mapper.typehandler

#logging:
#  level:
#    root: INFO

#server:
#  port: 18080
