spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    
  h2:
    console:
      enabled: true

mybatis:
  type-handlers-package: com.example.mapper.typehandler

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
#    root: DEBUG

#server:
#  port: 18080
